### ISSUE TITLE
dispatch] [card changer rework] handle: error running hook for S_LOAD_TOPO<3>

### ISSUE THREAD

**Issue by KiuviGonka** [odukjung/Card-Switch-Rework#4]
Hi can u help me whit that, i did all how says in the readme but always get that msg Q-Q

[20:25:20.601] [dispatch] [card changer rework] handle: error running hook for S_LOAD_TOPO<3>
hook: (anonymous) in card changer rework
data: {
  zone: 3105,
  loc: Vec3 { x: -84161, y: 134825, z: 4631 },
  quick: false
}
error: [dispatch] write: failed to generate C_DEACTIVATE_CARD_COMBINE_LIST<1>:
Error: code not known for message "C_DEACTIVATE_CARD_COMBINE_LIST"
    at Proxy.toServer (D:\TeraToolbox\bin\mod.js:333:30)
    at clearEffects (D:\TeraToolbox\mods\Card-Switch-Rework-main\index.js:956:17)
    at setPresetAndEffects (D:\TeraToolbox\mods\Card-Switch-Rework-main\index.js:943:9)
    at Object.callback (D:\TeraToolbox\mods\Card-Switch-Rework-main\index.js:149:7)

**Comment by KiuviGonka** [comment]
aw no answer, atleast  an not suported comment its ok :P

**Comment by odukjung** [comment]
plz read **INFO** before **USE**  / u dont have All effect set

Read Info first

**Comment by odukjung** [comment]
maybe u dont have NEW Effect card

read info first

**Comment by KiuviGonka** [comment]
i  have already the 37 list effect, 10 page set, just some of cards its still green, maybe its the wrong?

**Comment by KiuviGonka** [comment]
just a last question the  file  protocol.381290.map   work whit the current path of na tha is 384786? or should be a new protocol file?
